# Generated by Django 3.2.13 on 2022-10-29 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='갱신일')),
                ('d_day', models.PositiveSmallIntegerField(help_text='5 입력시 결제 5일전 발송', verbose_name='알람 발송일')),
                ('is_active', models.BooleanField(default=False, verbose_name='메일 발송 여부')),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_subscription', to='subscriptions.subscription', verbose_name='구독정보')),
            ],
            options={
                'verbose_name': '알림 정보',
                'verbose_name_plural': '알림 정보 목록',
            },
        ),
        migrations.CreateModel(
            name='AlarmHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='갱신일')),
                ('content', models.TextField(blank=True, default='', help_text='발송시 메일 내용을 그대로 넣어줍니다.', verbose_name='히스토리 내역')),
                ('is_success', models.BooleanField(default=False, verbose_name='발송 성공 여부')),
                ('traceback', models.TextField(blank=True, default='', verbose_name='발송 실패 원인')),
                ('alarm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alarms.alarm', verbose_name='알람')),
            ],
            options={
                'verbose_name': '알림 히스토리',
                'verbose_name_plural': '알림 히스토리 목록',
            },
        ),
    ]
