# Generated by Django 3.2.13 on 2022-11-24 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20221124_1746'),
        ('alarms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='alarm',
            name='d_day',
            field=models.SmallIntegerField(choices=[(-1, '미설정'), (1, '1일전'), (2, '2일전'), (3, '3일전'), (4, '4일전'), (5, '5일전'), (6, '6일전'), (7, '7일전')], help_text='선택 시, 해당 일자에 메일이 발송됩니다.', null=True, verbose_name='메일발송 D-DAY'),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='subscription',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alarm_subscription', to='subscriptions.subscription', verbose_name='구독정보'),
        ),
        migrations.AlterField(
            model_name='alarmhistory',
            name='alarm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alarms.alarm', verbose_name='알림'),
        ),
        migrations.AlterField(
            model_name='alarmhistory',
            name='traceback',
            field=models.TextField(blank=True, default='', null=True, verbose_name='발송 실패 원인'),
        ),
    ]
