# Generated by Django 3.2.13 on 2022-10-29 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='갱신일')),
                ('method', models.CharField(max_length=50, verbose_name='결제수단')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_user', to='users.user', verbose_name='유저')),
            ],
            options={
                'verbose_name': '결제 정보',
                'verbose_name_plural': '결제 정보 목록',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='갱신일')),
                ('type', models.PositiveSmallIntegerField(verbose_name='카테고리 종류')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리 목록',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='갱신일')),
                ('name', models.CharField(max_length=50, verbose_name='구독플랜')),
                ('price', models.PositiveIntegerField(verbose_name='가격')),
            ],
            options={
                'verbose_name': '구독 플랜',
                'verbose_name_plural': '구독 플랜 목록',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='갱신일')),
                ('started_at', models.DateTimeField(verbose_name='최초 구독일')),
                ('renewal', models.PositiveSmallIntegerField(verbose_name='구독 갱신일')),
                ('expire_at', models.PositiveSmallIntegerField(null=True, verbose_name='구독 만료일')),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_billing', to='subscriptions.billing', verbose_name='결제 정보')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.plan', verbose_name='구독플랜')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_user', to='users.user', verbose_name='유저')),
            ],
            options={
                'verbose_name': '사용자 구독 정보',
                'verbose_name_plural': '사용자 구독 정보 목록',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='갱신일')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='서비스명')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_category', to='subscriptions.category', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '서비스',
                'verbose_name_plural': '서비스 목록',
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_service', to='subscriptions.service', verbose_name='서비스'),
        ),
    ]
