# Generated by Django 3.2.13 on 2022-10-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='renewal',
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'OTT'), (2, '음악'), (3, '도서'), (4, '이커머스'), (5, '소프트웨어'), (6, '정기배송'), (7, '렌탈')], verbose_name='카테고리 종류'),
        ),
    ]
